# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
rojo = "rojo-rbx/rojo@7.4.4"
wally = "UpliftGames/wally@0.3.2"
lune = "lune-org/lune@0.8.9"
stylua = "JohnnyMorganz/StyLua@0.20.0"
wally-package-types = "JohnnyMorganz/wally-package-types@1.3.2"
