[package]
name = "scope/name"
version = "0.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
framework = "lumin/framework@9.0.0"
net = "lumin/net@0.5.0"
fusion = "elttob/fusion@0.3.0"
